### PR TITLE
fix: Create successful page

### PR DESCRIPTION
**Pull request by MysticalProgrammer**
Create successful page

### CODE REVIEW

**Review by xavi7th — CHANGES_REQUESTED** [review]
The design looks good. Just one or two corrections

1. In mobile view the text padding is off. Also increase the font size a bit for easier reading and better relative size with the image. 
2. Also reduce the top padding.
image


3. In desktop size, increase the size of the font, and reduce the top padding to center it more.
image


4. For tablets all we need to do is icrease the font-size. I think 3 will also take care of this

image

5. The dark mode is not optimised at all. As we build the new components, let's at lease make fonts and backgrounds dark mode compatible at once since we are using tailwind and we will still need to do it later. Later on, we can go back and do a more thorough cleanup of the dark mode.

image

**Comment by xavi7th** [comment]
@MysticalProgrammer please review

**Comment by MysticalProgrammer** [comment]
@xavi7th the changes has been completed
Screenshot 2024-10-01 at 12 14 58

**Comment by MysticalProgrammer** [comment]
@xavi7th 
localhost_5173_store_successful(iPhone SE)

**Review by xavi7th — APPROVED** [review]

**Pull request merged**
