### PR TITLE
design: create registration page

### PR DESCRIPTION
**Pull request by MysticalProgrammer**
create registration page

### CODE REVIEW

**Review by xavi7th — CHANGES_REQUESTED** [review]
image

Change the "Or continue with" to just "Or" and then use a divider from preline like we have in this example https://preline.co/docs/dividers.html#vertical-button-grpup-with-label

**Review by xavi7th — CHANGES_REQUESTED** [review]
image

The "sign up" and the "terms and conditions color" is too light in light mode. Darken a bit.

image

Then the dark-mode background of the form is bright. Just adjust accordingly.

**Comment by MysticalProgrammer** [comment]
@xavi7th this is done

**Comment by MysticalProgrammer** [comment]
@xavi7th 
localhost_5173_register(iPhone SE)
localhost_5173_register

**Review by xavi7th — APPROVED** [review]

**Pull request merged**
